etl:
  source:
    database: mimic
    connection:
      type: postgres
      host: localhost
      port: 5432
      user: mimic_user
      password: mimic_password
      database: mimic_db

  target:
    database: omop
    connection:
      type: postgres
      host: localhost
      port: 5432
      user: omop_user
      password: omop_password
      database: omop_db

  steps:
    extract: []
    transform: []
    load: []
