admissions:
  table_name: admissions
  columns:
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
      primary_key: true
    admittime:
      type: String
    dischtime:
      type: String
    deathtime:
      type: String
    admission_type:
      type: String
    admit_provider_id:
      type: String
    admission_location:
      type: String
    discharge_location:
      type: String
    insurance:
      type: String
    language:
      type: String
    marital_status:
      type: String
    race:
      type: String
    edregtime:
      type: String
    edouttime:
      type: String
    hospital_expire_flag:
      type: Integer

patients:
  table_name: patients
  columns:
    subject_id:
      type: Integer
      primary_key: true
    gender:
      type: String
    anchor_age:
      type: Integer
    anchor_year:
      type: Integer
    anchor_year_group:
      type: String
    dod:
      type: String
