etl:
  source:
    type: csv
    directory: ./data/source
    schema_file: source_schema.yaml
  target:
    type: csv
    directory: ./data/target
    schema_file: target_schema.yaml
  mappings:
    - source_table: patients
      target_table: person
      column_mappings: person_mapping

