person_mapping:
  - source_column: subject_id
    add_column: person_id

  - source_column: dob
    add_column: birth_datetime

  - source_column: gender
    add_column: gender_concept_id
    transformation:
      type: map
      values:
        M: 8507  # Male
        F: 8532  # Female
