staging_person_lookup:
  source_table: patients
  target_table: staging_person_lookup
  columns:
    - target_column: person_id
      transformation:
        type: generate_id
    - target_column: subject_id
      transformation:
        type: copy
        source_column: subject_id

tmp_subject_race:
  source_table: admissions
  target_table: tmp_subject_race
  columns:
    - target_column: subject_id
      transformation:
        type: copy
        source_column: subject_id
    - target_column: race
      transformation:
        type: aggregate
        source_columns:
          - subject_id
          - admittime
          - race
        group_by:
          - subject_id
          - admittime
        order_by: admittime
        aggregation: first

person_mapping:
  source_table: patients
  target_table: person
  columns:
    - target_column: person_id
      transformation:
        type: link
        linked_table: staging_person_lookup
        link_column: subject_id
        source_column: person_id
    - target_column: gender_concept_id
      transformation:
        type: conditional_map
        source_column: gender
        conditions:
          - condition: "gender == 'F'"
            value: 8532  # FEMALE
          - condition: "gender == 'M'"
            value: 8507  # MALE
        default: 0
    - target_column: year_of_birth
      transformation:
        type: derive
        source_columns:
          - anchor_year
          - anchor_age
        formula: "anchor_year - anchor_age"
    - target_column: month_of_birth
      transformation:
        type: default
        value: 
    - target_column: day_of_birth
      transformation:
        type: default
        value: null
    - target_column: birth_datetime
      transformation:
        type: default
        value: null
    - target_column: race_concept_id
      transformation:
        type: default
        value: 
    - target_column: ethnicity_concept_id
      transformation:
        type: default
        value: 
    - target_column: location_id
      transformation:
        type: default
        value: null
    - target_column: provider_id
      transformation:
        type: default
        value: null
    - target_column: care_site_id
      transformation:
        type: default
        value: null
    - target_column: person_source_value
      transformation:
        type: copy
        source_column: subject_id
    - target_column: gender_source_value
      transformation:
        type: copy
        source_column: gender
    - target_column: gender_source_concept_id
      transformation:
        type: default
        value: 0
    - target_column: race_source_value
      transformation:
        type: default
        value: 
    - target_column: race_source_concept_id
      transformation:
        type: default
        value: 
    - target_column: ethnicity_source_value
      transformation:
        type: default
        value: 
    - target_column: ethnicity_source_concept_id
      transformation:
        type: default
        value:
    - target_column: ethnicity
      transformation:
        type: link
        linked_table: admissions
        link_column: subject_id
        source_column: race
        aggregation:
          method: most_frequent
