person_mapping:
  source_table: patients
  target_table: person
  transformations:
    - source_column: subject_id
      target_column: person_id
    - source_column: gender
      target_column: gender_concept_id
      transformation:
        type: map
        values:
          M: 8507
          F: 8532
