person_mapping:
  source_table: patients
  target_table: person
  columns:
    - target_column: person_id
      transformation:
        type: generate_id
    - target_column: gender_concept_id
      transformation:
        type: map
        source_column: gender
        values:
          M: 8507
          F: 8532
    - target_column: year_of_birth
      transformation:
        type: derive
        source_columns:
          - anchor_year
          - anchor_age
        formula: "anchor_year - anchor_age"
    - target_column: month_of_birth
      transformation:
        type: default
        value: 
    - target_column: day_of_birth
      transformation:
        type: default
        value: 
    - target_column: birth_datetime
      transformation:
        type: default
        value: 
    - target_column: race_concept_id
      transformation:
        type: default
        value: 
    - target_column: ethnicity_concept_id
      transformation:
        type: default
        value: 
    - target_column: location_id
      transformation:
        type: default
        value: 
    - target_column: provider_id
      transformation:
        type: default
        value: 
    - target_column: care_site_id
      transformation:
        type: default
        value: 
    - target_column: person_source_value
      transformation:
        type: default
        value: 
    - target_column: gender_source_value
      transformation:
        type: default
        value: 
    - target_column: gender_source_concept_id
      transformation:
        type: default
        value: 0
    - target_column: race_source_value
      transformation:
        type: default
        value: 
    - target_column: race_source_concept_id
      transformation:
        type: default
        value: 
    - target_column: ethnicity_source_value
      transformation:
        type: default
        value: 
    - target_column: ethnicity_source_concept_id
      transformation:
        type: default
        value:
    - target_column: ethnicity
      transformation:
        type: link
        linked_table: admissions
        link_column: subject_id
        source_column: race
        aggregation:
          method: most_frequent

death_mapping:
  source_table: admissions
  target_table: death
  columns:
    - target_column: person_id
      transformation:
        type: generate_id
    - target_column: death_date
      transformation:
        type: compare_deathtime
        source_column_1: deathtime
        source_column_2: dischtime
    - target_column: death_datetime
      transformation:
        type: compare_deathtime
        source_column_1: deathtime
        source_column_2: dischtime
    - target_column: death_type_concept_id
      transformation:
        type: default
        value: 32817
    - target_column: cause_concept_id
      transformation:
        type: default
        value:
    - target_column: cause_source_value
      transformation:
        type: default
        value:
    - target_column: cause_source_concept_id
      transformation:
        type: default
        value:
    - target_column: unit_id
      transformation:
        type: default
        value:
    - target_column: load_table_id
      transformation:
        type: default
        value:
    - target_column: load_row_id
      transformation:
        type: default
        value:
    - target_column: trace_id
      transformation:
        type: default
        value: 
