patients:
  table_name: patients
  columns:
    subject_id:
      type: Integer
      primary_key: true
    gender:
      type: String
    dob:
      type: DateTime

admissions:
  table_name: admissions
  columns:
    hadm_id:
      type: Integer
      primary_key: true
    subject_id:
      type: Integer
    admittime:
      type: DateTime
    dischtime:
      type: DateTime
    admission_type:
      type: String
