patients:
  table_name: patients
  columns:
    subject_id:
      type: Integer
      primary_key: true
    gender:
      type: String
    dob:
      type: DateTime
    dod:
      type: DateTime

admissions:
  table_name: admissions
  columns:
    hadm_id:
      type: Integer
      primary_key: true
    subject_id:
      type: Integer
    admittime:
      type: DateTime
    dischtime:
      type: DateTime
    admission_type:
      type: String

transfers:
  table_name: transfers
  columns:
    transfer_id:
      type: Integer
    hadm_id:
      type: Integer
    transfer_time:
      type: DateTime
    leave_time:
      type: DateTime
    service:
      type: String

icustays:
  table_name: icustays
  columns:
    stay_id:
      type: Integer
      primary_key: true
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
    intime:
      type: DateTime
    outtime:
      type: DateTime

diagnoses_icd:
  table_name: diagnoses_icd
  columns:
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
    icd_code:
      type: String
    icd_version:
      type: Integer
    seq_num:
      type: Integer

procedures_icd:
  table_name: procedures_icd
  columns:
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
    icd_code:
      type: String
    icd_version:
      type: Integer

labevents:
  table_name: labevents
  columns:
    itemid:
      type: Integer
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
    charttime:
      type: DateTime
    value:
      type: String
    valuenum:
      type: Float
    valueuom:
      type: String

chartevents:
  table_name: chartevents
  columns:
    itemid:
      type: Integer
    subject_id:
      type: Integer
    hadm_id:
      type: Integer
    charttime:
      type: DateTime
    value:
      type: String
    valuenum:
      type: Float
    valueuom:
      type: String
