person:
  columns:
    person_id:
      type: String
      primary_key: true
    gender_concept_id:
      type: Integer
    year_of_birth:
      type: Integer
    month_of_birth:
      type: Integer
    day_of_birth:
      type: Integer
    birth_datetime:
      type: DateTime
    race_concept_id:
      type: Integer
    ethnicity_concept_id:
      type: Integer
    location_id:
      type: Integer
    provider_id:
      type: Integer
    care_site_id:
      type: Integer
    person_source_value:
      type: String
    gender_source_value:
      type: String
    gender_source_concept_id:
      type: Integer
    race_source_value:
      type: String
    race_source_concept_id:
      type: Integer
    ethnicity_source_value:
      type: String
    ethnicity_source_concept_id:
      type: Integer
    ethnicity:
      type: String

