name: Runs pytest

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        # install omopetl
        pip install -e .

    - name: Run template tests
      run: pytest tests

    - name: Test omopetl CLI commands
      run: |
        # Create a demo project
        omopetl startdemo DEMO

        # Run the ETL in dry mode
        omopetl run DEMO
